"use client";

import { ArrowDownTrayIcon, CheckIcon, EnvelopeIcon, TrashIcon, XMarkIcon } from "@heroicons/react/24/outline";

import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DonutChart, SimpleBarChart, SimpleLineChart } from "@/components/charts/charts";
import { exportText } from "@/lib/utils/export";
import type { ChatAttachment } from "@/lib/data/types";

export function MessageAttachment({
  attachment,
  onUpdate,
  onToast,
}: {
  attachment: ChatAttachment;
  onUpdate: (patch: Partial<ChatAttachment>) => void;
  onToast: (title: string, description?: string) => void;
}) {
  if (attachment.kind === "chart") {
    return (
      <div className="bg-card mt-3 rounded-lg border p-3">
        <div className="mb-1 flex items-center justify-between">
          <p className="text-sm font-medium">{attachment.title}</p>
          <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={() => onToast("Chart exported", `${attachment.title}.png`)}>
            <ArrowDownTrayIcon /> PNG
          </Button>
        </div>
        {attachment.chartType === "donut" && <DonutChart data={attachment.data} height={220} />}
        {attachment.chartType === "bar" && <SimpleBarChart data={attachment.data} height={220} layout={attachment.data.length > 4 ? "horizontal" : "vertical"} colorByName />}
        {attachment.chartType === "line" && (
          <SimpleLineChart data={attachment.data.map((d) => ({ name: d.name, value: d.value }))} xKey="name" series={[{ key: "value", label: attachment.title }]} height={220} />
        )}
      </div>
    );
  }

  if (attachment.kind === "table") {
    return (
      <div className="bg-card mt-3 overflow-hidden rounded-lg border">
        <div className="flex items-center justify-between border-b px-3 py-2">
          <p className="text-sm font-medium">{attachment.title}</p>
          <Button
            variant="ghost"
            size="sm"
            className="h-7 text-xs"
            onClick={() => exportText(`${attachment.title.replace(/\s+/g, "_")}.csv`, [attachment.columns.join(","), ...attachment.rows.map((r) => r.join(","))].join("\n"), "text/csv")}
          >
            <ArrowDownTrayIcon /> CSV
          </Button>
        </div>
        <Table>
          <TableHeader>
            <TableRow>{attachment.columns.map((c) => <TableHead key={c}>{c}</TableHead>)}</TableRow>
          </TableHeader>
          <TableBody>
            {attachment.rows.map((r, i) => (
              <TableRow key={i}>{r.map((c, j) => <TableCell key={j} className="text-xs">{c}</TableCell>)}</TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    );
  }

  if (attachment.kind === "file") {
    const mime = attachment.ext === "md" ? "text/markdown" : "text/plain";
    return (
      <div className="bg-card mt-3 flex items-center justify-between gap-3 rounded-lg border p-3">
        <div className="flex items-center gap-3">
          <Badge variant="outline" className="uppercase">{attachment.ext}</Badge>
          <div>
            <p className="text-sm font-medium">{attachment.name}</p>
            <p className="text-muted-foreground text-xs">Generated by the local LLM · {attachment.content.length} chars</p>
          </div>
        </div>
        <Button size="sm" variant="outline" onClick={() => { exportText(attachment.name, attachment.content, mime); onToast("Download started", attachment.name); }}>
          <ArrowDownTrayIcon /> Download
        </Button>
      </div>
    );
  }

  if (attachment.kind === "email-draft") {
    return (
      <div className="bg-card mt-3 rounded-lg border">
        <div className="flex items-center gap-2 border-b px-3 py-2 text-sm font-medium"><EnvelopeIcon className="size-4" /> Email draft {attachment.status !== "pending" && <Badge variant={attachment.status === "sent" ? "success" : "secondary"} className="ml-auto capitalize">{attachment.status}</Badge>}</div>
        <div className="space-y-1 px-3 py-2 text-sm">
          <p><span className="text-muted-foreground">To:</span> {attachment.to || "—"}</p>
          <p><span className="text-muted-foreground">Subject:</span> {attachment.subject}</p>
          <pre className="bg-muted/50 mt-2 rounded-md p-3 font-sans text-xs whitespace-pre-wrap">{attachment.body}</pre>
        </div>
        {attachment.status === "pending" && (
          <div className="flex justify-end gap-2 border-t px-3 py-2">
            <Button size="sm" variant="outline" onClick={() => onUpdate({ status: "cancelled" })}><XMarkIcon /> Cancel</Button>
            <Button size="sm" onClick={() => { onUpdate({ status: "sent" }); onToast("Email sent", attachment.subject); }}><CheckIcon /> Confirm & send</Button>
          </div>
        )}
      </div>
    );
  }

  if (attachment.kind === "email-delete") {
    return (
      <div className="bg-card mt-3 rounded-lg border">
        <div className="flex items-center gap-2 border-b px-3 py-2 text-sm font-medium"><TrashIcon className="size-4" /> Delete email {attachment.status !== "pending" && <Badge variant="secondary" className="ml-auto capitalize">{attachment.status}</Badge>}</div>
        <p className="px-3 py-2 text-sm"><span className="text-muted-foreground">Subject:</span> {attachment.subject}</p>
        {attachment.status === "pending" && (
          <div className="flex justify-end gap-2 border-t px-3 py-2">
            <Button size="sm" variant="outline" onClick={() => onUpdate({ status: "cancelled" })}>Keep</Button>
            <Button size="sm" variant="destructive" onClick={() => { onUpdate({ status: "deleted" }); onToast("Email deleted"); }}><TrashIcon /> Confirm delete</Button>
          </div>
        )}
      </div>
    );
  }

  return null;
}
